### ISSUE TITLE
WebLogic Warning: This server is not secure. Upgrade to Java 1.8.0_181 or higher

### ISSUE THREAD

**Issue by galiacheng** [wls-eng/arm-oraclelinux-wls#196] opened 2020-11-18 05:20 UTC
Screenshot:
![image](https://user-images.githubusercontent.com/59823457/99486805-e3018a80-299f-11eb-8720-32b09809c061.png)

on images: 
 "owls-122130-8u131-ol73;Oracle:weblogic-122130-jdk8u131-ol73:owls-122130-8u131-ol7;latest"
 "owls-122130-8u131-ol74;Oracle:weblogic-122130-jdk8u131-ol74:owls-122130-8u131-ol7;latest"

TBD:
1. create the images with new jdk version.
2. create new offers in partner center, we can not change the existing offer id, to keep the offer id matched with java version, we have to create new offers for the new images.
3. remove(disable) existing image offers
4. update ARM template for 4 wls offers, and update the offers in partner center
5. update `build.yaml` in 4 wls repos and test the offers via CI/CD

**Comment by galiacheng** [comment] 2020-11-18 05:22
Hello @edburns  @jacobt123 FYI, please review the actions and add you comment.

**Comment by jacobt123** [comment] 2020-11-18 05:51
Yes @sanjaymantoor pointed this out over the weekend and this is one of the issues I was planning on discussing with @edburns during our weekly meeting. My suggestion would be to do away with images with specific JDK versions and have one image per version of WLS + OL. We will have to keep the image updated with the latest Java CPU and the latest quarterly WLS patch. So at any given point the image available on marketplace would contain the latest JDK (on which WLS is certified) and latest WLS quarterly patch.

**Comment by galiacheng** [comment] 2020-11-18 06:10
@jacobt123 thanks for your quick update! So we will rename all the images, removing the jdk version, right?

**Comment by edburns** [comment] 2020-11-18 19:27
@jacobt123  and @edburns  discussed this today and defined the following way forward:

1. Publish a new set of five base images, one for each of the existing base images
    * Each image is a duplicate of the corresponding existing one, the only difference being the name/offerid/SKU/URN does not have the "uNNN" portion.  Instead it would have "jdk8" or "jdk11".
   * Each image is the same in every other way.
   * The "offer listing" text for each image **will** show the exact version number.
2. When the new images are live, make the following updates to the Azure Applications
   * Any place where the URN is referenced, update it to the new URN.
   * In `createUiDefinition.json` update the text to say the exact JDK version, even though it is not included in the URN.
   * Modify the `build.yml` files for the CI/CD pipelines to take these changes into account.
   * Modify the documentation, if necessary.

**Comment by edburns** [comment] 2020-12-02 21:47
Hello @jacobt123, as discussed today, I have created the **20201202-hotfix branches**.
* https://github.com/wls-eng/arm-oraclelinux-wls/tree/20201202-hotfix
* https://github.com/wls-eng/arm-oraclelinux-wls-admin/tree/20201202-hotfix
* https://github.com/wls-eng/arm-oraclelinux-wls-cluster/tree/20201202-hotfix
* https://github.com/wls-eng/arm-oraclelinux-wls-dynamic-cluster/tree/20201202-hotfix
Please have your team submit the PRs to these branches.

**Comment by edburns** [comment] 2020-12-09 22:20
merged arm-oralcelinux-wls
merged arm-oraclelinux-wls-admin

**Comment by edburns** [comment] 2021-01-05 00:55
![image](https://user-images.githubusercontent.com/75821/103594495-d640e380-4ec6-11eb-9c3f-789dbff9a8b3.png)
Resolved.

**Closed by edburns** 2021-01-05 00:55 UTC
