### ISSUE TITLE
ELK deployment failed with creating index conflict

### ISSUE THREAD

**Issue by zhengchang907** [wls-eng/arm-oraclelinux-wls#281] opened 2021-03-01 09:42 UTC
```
{
  "code": "DeploymentFailed",
  "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.",
  "details": [
    {
      "code": "VMExtensionProvisioningError",
      "message": "VM has reported a failure when processing extension 'newuserscript'. Error message: \"Enable failed: failed to execute command: command terminated with exit status=1\n[stdout]\n{\"error\":{\"root_cause\":[{\"type\":\"resource_already_exists_exception\",\"reason\":\"index [azure-weblogic-validate-elastic-server-1614589505/_J6TYMZBSACNQUUYAA-alw] already exists\",\"index_uuid\":\"_J6TYMZBSACNQUUYAA-alw\",\"index\":\"azure-weblogic-validate-elastic-server-1614589505\"}],\"type\":\"resource_already_exists_exception\",\"reason\":\"index [azure-weblogic-validate-elastic-server-1614589505/_J6TYMZBSACNQUUYAA-alw] already exists\",\"index_uuid\":\"_J6TYMZBSACNQUUYAA-alw\",\"index\":\"azure-weblogic-validate-elastic-server-1614589505\"},\"status\":400}\n\n[stderr]\n  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n                                 Dload  Upload   Total   Spent    Left  Speed\n\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\r100   537  100   537    0     0   1684      0 --:--:-- --:--:-- --:--:--  1683\n\"\r\n\r\nMore information on troubleshooting is available at https://aka.ms/VMExtensionCSELinuxTroubleshoot "
    }
  ]
}
```
It seems that 2 vms tried to create index at the same time, using the same timestamp

**Comment by galiacheng** [comment] 2021-03-01 10:13
This is an intermittent issue caused by two vm use the same index to validate the elk server. we can fix it soon.

**Comment by galiacheng** [comment] 2021-03-02 09:41
Hello @zhengchang907  I have PRs for this issue, please have a check after the PRs are merged.

**Closed** 2021-03-02 17:15 UTC
